global using FluentValidation;
global using MediatR;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
global using Domain.Entities;
global using Application.Interfaces.Repositories;
global using Application.Utils;
global using Application.Wrappers;
global using Domain.Enums;